### ISSUE TITLE
Commented out code

### ISSUE THREAD

**Issue by ericou1** [Fanuel-D/Final-Project#11]
Don't push commented out code

https://github.com/Fanuel-D/Final-Project/blob/5223fbbd2686ee4517ea72be8fd92663a0018215/frontend/src/components/ParsedPDFHandler.jsx#L29

https://github.com/Fanuel-D/Final-Project/blob/5223fbbd2686ee4517ea72be8fd92663a0018215/frontend/src/components/HomePage.jsx#L59

https://github.com/Fanuel-D/Final-Project/blob/5223fbbd2686ee4517ea72be8fd92663a0018215/backend/index.js#L13

Also don't push with console.log

https://github.com/Fanuel-D/Final-Project/blob/5223fbbd2686ee4517ea72be8fd92663a0018215/frontend/src/components/ParsedPDFHandler.jsx#L12

**Comment by Fanuel-D** [comment]
resolved
