### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by Samantha-Zhao** [Fanuel-D/Final-Project#13]
https://github.com/Fanuel-D/Final-Project/blob/5223fbbd2686ee4517ea72be8fd92663a0018215/frontend/src/components/HomePage.jsx#L59

**Comment by Samantha-Zhao** [comment]
https://github.com/Fanuel-D/Final-Project/blob/5223fbbd2686ee4517ea72be8fd92663a0018215/frontend/src/components/ParsedPDFHandler.jsx#L29

**Comment by Fanuel-D** [comment]
resolved
