### ISSUE TITLE
Wrong api endpoint

### ISSUE THREAD

**Issue by Stannie-Lim** [Fanuel-D/Final-Project#2]
https://github.com/Fanuel-D/Final-Project/blob/8ace2b7fbeafde66c03d1b6c79431c9e79c374c5/frontend/src/components/App.jsx#L21

from here https://github.com/Fanuel-D/Final-Project/blob/user-authentication/backend/index.js#L10 and  https://github.com/Fanuel-D/Final-Project/blob/user-authentication/backend/routes/auth.js#L41 i see that this api endpoint is actually /auth/users/login rather than just /users/login

also it's a post, not a get (´・◡・｀) 

however, i think you were trying to send a request to this route https://github.com/Fanuel-D/Final-Project/blob/user-authentication/backend/routes/auth.js#L63 because it seems like you're just trying to transform the token -> user

**Comment by Fanuel-D** [comment]
My bad this is what I had yesterday I only pushed the backend for my recent push
